# Installed optional host components. The exact sequence package never loads CE.
function(_baseplane_substrate_check_graph target stack)
    get_target_property(canonical "${target}" ALIASED_TARGET)
    if(canonical)
        set(target "${canonical}")
    endif()
    if("${target}" IN_LIST stack)
        message(FATAL_ERROR "Baseplane substrate target cycle at ${target}")
    endif()
    list(APPEND stack "${target}")
    get_target_property(links "${target}" INTERFACE_LINK_LIBRARIES)
    foreach(link IN LISTS links)
        if(TARGET "${link}")
            _baseplane_substrate_check_graph("${link}" "${stack}")
        endif()
    endforeach()
endfunction()

function(_baseplane_substrate_header header)
    get_target_property(includes Baseplane::seq INTERFACE_INCLUDE_DIRECTORIES)
    foreach(directory IN LISTS includes)
        if(EXISTS "${directory}/${header}")
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "Baseplane component header unavailable in installed package: ${header}")
endfunction()

function(_baseplane_substrate_require_provider provider)
    if(NOT TARGET "${provider}")
        message(FATAL_ERROR "Missing selected installed CE capability: ${provider}")
    endif()
    get_target_property(imported "${provider}" IMPORTED)
    if(NOT imported)
        message(FATAL_ERROR "Selected CE capability must be imported from its installed package: ${provider}")
    endif()
    _baseplane_substrate_check_graph("${provider}" "")
endfunction()

function(baseplane_load_substrate)
    cmake_parse_arguments(BP "REQUIRE_CUDA" "CE_PACKAGE" "COMPONENTS" ${ARGN})
    if(BP_UNPARSED_ARGUMENTS OR NOT BP_COMPONENTS OR NOT TARGET Baseplane::seq)
        message(FATAL_ERROR "Load installed Baseplane::seq and specify substrate COMPONENTS")
    endif()
    get_target_property(seq_imported Baseplane::seq IMPORTED)
    if(NOT seq_imported)
        message(FATAL_ERROR "Substrate install interface requires imported Baseplane::seq")
    endif()
    if(NOT BP_CE_PACKAGE)
        set(BP_CE_PACKAGE Cellerator)
    endif()
    set(needs_ce FALSE)
    set(ce_components "")
    foreach(component IN LISTS BP_COMPONENTS)
        if(component STREQUAL query)
            set(header Baseplane/query/contracts/sequence_question.hh)
        elseif(component STREQUAL hierarchy)
            set(header Baseplane/representation/hierarchy.hh)
            set(needs_ce TRUE)
            list(APPEND ce_components moonshot_effects)
        elseif(component STREQUAL index)
            set(header Baseplane/index/sequence_index.hh)
            set(needs_ce TRUE)
            list(APPEND ce_components moonshot_mechanisms)
        elseif(component STREQUAL reuse)
            set(header Baseplane/incremental/reuse.hh)
        elseif(component STREQUAL learning)
            set(header Baseplane/learning/sequence_routes.hh)
            set(needs_ce TRUE)
            list(APPEND ce_components moonshot_learning)
        else()
            message(FATAL_ERROR "Unknown Baseplane substrate component: ${component}")
        endif()
        _baseplane_substrate_header("${header}")
    endforeach()
    if(BP_REQUIRE_CUDA)
        message(FATAL_ERROR "Requested Baseplane substrate components expose host APIs; CUDA execution is unavailable")
    endif()
    if(needs_ce)
        # This is an installed config lookup, never add_subdirectory(sibling).
        list(REMOVE_DUPLICATES ce_components)
        find_package(${BP_CE_PACKAGE} CONFIG REQUIRED COMPONENTS ${ce_components})
    endif()
    foreach(component IN LISTS BP_COMPONENTS)
        set(provider "")
        if(component STREQUAL hierarchy)
            set(provider Cellerator::moonshot_effects)
        elseif(component STREQUAL index)
            set(provider Cellerator::moonshot_mechanisms)
        elseif(component STREQUAL learning)
            set(provider Cellerator::moonshot_learning)
        endif()
        if(provider)
            _baseplane_substrate_require_provider("${provider}")
        endif()
        if(NOT TARGET "Baseplane::${component}")
            add_library("Baseplane::${component}" INTERFACE IMPORTED GLOBAL)
            set_property(TARGET "Baseplane::${component}" PROPERTY
                INTERFACE_LINK_LIBRARIES "Baseplane::seq;${provider}")
            set_property(TARGET "Baseplane::${component}" PROPERTY
                INTERFACE_COMPILE_FEATURES cxx_std_17)
            set_property(TARGET "Baseplane::${component}" PROPERTY BASEPLANE_HOST_AVAILABLE TRUE)
            set_property(TARGET "Baseplane::${component}" PROPERTY BASEPLANE_CUDA_AVAILABLE FALSE)
        endif()
        _baseplane_substrate_check_graph("Baseplane::${component}" "")
        set("Baseplane_${component}_FOUND" TRUE PARENT_SCOPE)
    endforeach()
endfunction()
