# Opt-in integration seam: callers select real numerical components.
# Loading this module does not change the standalone Baseplane::seq target.
function(baseplane_add_representation_target target)
    cmake_parse_arguments(BP "" "" "COMPONENTS" ${ARGN})
    if(BP_UNPARSED_ARGUMENTS OR NOT BP_COMPONENTS)
        message(FATAL_ERROR "${target}: specify COMPONENTS with explicit Cellerator targets")
    endif()
    if(NOT TARGET Baseplane::seq)
        message(FATAL_ERROR "${target}: load Baseplane::seq first")
    endif()
    foreach(component IN LISTS BP_COMPONENTS)
        if(NOT component MATCHES "^Cellerator::" OR NOT TARGET "${component}")
            message(FATAL_ERROR "${target}: unavailable numerical component ${component}")
        endif()
        if(component MATCHES "^Cellerator::(cellerator|moonshot)$")
            message(FATAL_ERROR "${target}: select numerical components individually")
        endif()
    endforeach()
    add_library(${target} INTERFACE)
    target_link_libraries(${target} INTERFACE Baseplane::seq ${BP_COMPONENTS})
    target_compile_features(${target} INTERFACE cxx_std_17)
endfunction()
